repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.10.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate_no_variables
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: check-merge-conflict
